version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "org.jetbrains.compose"
      - dependency-name: "org.jetbrains.compose.components:components-resources"
      - dependency-name: "org.jetbrains.compose.foundation:foundation"
      - dependency-name: "org.jetbrains.compose.material3.adaptive:adaptive-navigation3"
      - dependency-name: "org.jetbrains.compose.material3:material3"
      - dependency-name: "org.jetbrains.compose.runtime:runtime"
      - dependency-name: "org.jetbrains.compose.ui:ui"
      - dependency-name: "org.jetbrains.compose.ui:ui-tooling"
      - dependency-name: "org.jetbrains.compose.ui:ui-tooling-preview"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
